import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SectionContainer from "@/components/SectionContainer";
import LayoutWrapper from "@/components/LayoutWrapper";
import { RootProvider } from "fumadocs-ui/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <LayoutWrapper><RootProvider>{children}</RootProvider></LayoutWrapper>
          
        
      </body>
    </html>
  );
}
