import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "@/context/ThemeContext";
import ThemeProvider from "@/providers/ThemeProvider";
import LayoutWrapper from "@/components/LayoutWrapper";
import { RootProvider } from "fumadocs-ui/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeContextProvider>
        <ThemeProvider>
          <LayoutWrapper>
            <RootProvider>{children}</RootProvider>
          </LayoutWrapper>
        </ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
